version: "3.9"

services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    environment:
      - COCKROACH_USERNAME=root
      - COCKROACH_PASSWORD=root
      - COCKROACH_LOG_STMTS=all
    volumes:
      - ./deployments/cockroachdb/setup.sh:/cockroachdb/setup.sh
    healthcheck:
      test: [ "CMD-SHELL", "cockroach node status --insecure" ]
      interval: 10s
      timeout: 5s
      retries: 5


  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_ALLOW_EVERYONE_IF_NO_ACL_FOUND=true
    depends_on:
      - zookeeper

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
