// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: manager/events/manager.proto

package events

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManagerRole int32

const (
	ManagerRole_MANAGER_ROLE_UNDEFINED ManagerRole = 0
	ManagerRole_MANAGER_ROLE_ADMIN     ManagerRole = 1
	ManagerRole_MANAGER_ROLE_MODERATOR ManagerRole = 2
)

// Enum value maps for ManagerRole.
var (
	ManagerRole_name = map[int32]string{
		0: "MANAGER_ROLE_UNDEFINED",
		1: "MANAGER_ROLE_ADMIN",
		2: "MANAGER_ROLE_MODERATOR",
	}
	ManagerRole_value = map[string]int32{
		"MANAGER_ROLE_UNDEFINED": 0,
		"MANAGER_ROLE_ADMIN":     1,
		"MANAGER_ROLE_MODERATOR": 2,
	}
)

func (x ManagerRole) Enum() *ManagerRole {
	p := new(ManagerRole)
	*p = x
	return p
}

func (x ManagerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManagerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_manager_events_manager_proto_enumTypes[0].Descriptor()
}

func (ManagerRole) Type() protoreflect.EnumType {
	return &file_manager_events_manager_proto_enumTypes[0]
}

func (x ManagerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManagerRole.Descriptor instead.
func (ManagerRole) EnumDescriptor() ([]byte, []int) {
	return file_manager_events_manager_proto_rawDescGZIP(), []int{0}
}

type ManagerEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManagerId string `protobuf:"bytes,1,opt,name=managerId,proto3" json:"managerId,omitempty"`
	// Types that are assignable to Event:
	//
	//	*ManagerEvent_ManagerCreated
	Event isManagerEvent_Event `protobuf_oneof:"event"`
}

func (x *ManagerEvent) Reset() {
	*x = ManagerEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manager_events_manager_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerEvent) ProtoMessage() {}

func (x *ManagerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_manager_events_manager_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerEvent.ProtoReflect.Descriptor instead.
func (*ManagerEvent) Descriptor() ([]byte, []int) {
	return file_manager_events_manager_proto_rawDescGZIP(), []int{0}
}

func (x *ManagerEvent) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (m *ManagerEvent) GetEvent() isManagerEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ManagerEvent) GetManagerCreated() *ManagerCreated {
	if x, ok := x.GetEvent().(*ManagerEvent_ManagerCreated); ok {
		return x.ManagerCreated
	}
	return nil
}

type isManagerEvent_Event interface {
	isManagerEvent_Event()
}

type ManagerEvent_ManagerCreated struct {
	ManagerCreated *ManagerCreated `protobuf:"bytes,2,opt,name=managerCreated,proto3,oneof"`
}

func (*ManagerEvent_ManagerCreated) isManagerEvent_Event() {}

type ManagerCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName  string                 `protobuf:"bytes,1,opt,name=fullName,proto3" json:"fullName,omitempty"`
	Role      ManagerRole            `protobuf:"varint,2,opt,name=role,proto3,enum=api.manager.events.ManagerRole" json:"role,omitempty"`
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *ManagerCreated) Reset() {
	*x = ManagerCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_manager_events_manager_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ManagerCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManagerCreated) ProtoMessage() {}

func (x *ManagerCreated) ProtoReflect() protoreflect.Message {
	mi := &file_manager_events_manager_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManagerCreated.ProtoReflect.Descriptor instead.
func (*ManagerCreated) Descriptor() ([]byte, []int) {
	return file_manager_events_manager_proto_rawDescGZIP(), []int{1}
}

func (x *ManagerCreated) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *ManagerCreated) GetRole() ManagerRole {
	if x != nil {
		return x.Role
	}
	return ManagerRole_MANAGER_ROLE_UNDEFINED
}

func (x *ManagerCreated) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_manager_events_manager_proto protoreflect.FileDescriptor

var file_manager_events_manager_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12,
	0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x4c, 0x0a, 0x0e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x4d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x0e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x9b, 0x01, 0x0a, 0x0e, 0x4d, 0x61,
	0x6e, 0x61, 0x67, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x61, 0x6e,
	0x61, 0x67, 0x65, 0x72, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x4d, 0x61, 0x6e, 0x61,
	0x67, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x38, 0x0a,
	0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x2a, 0x5d, 0x0a, 0x0b, 0x4d, 0x61, 0x6e, 0x61, 0x67,
	0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45,
	0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x16, 0x0a, 0x12, 0x4d, 0x41, 0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x52, 0x4f,
	0x4c, 0x45, 0x5f, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4d, 0x41,
	0x4e, 0x41, 0x47, 0x45, 0x52, 0x5f, 0x52, 0x4f, 0x4c, 0x45, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x52,
	0x41, 0x54, 0x4f, 0x52, 0x10, 0x02, 0x42, 0x10, 0x5a, 0x0e, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65,
	0x72, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_manager_events_manager_proto_rawDescOnce sync.Once
	file_manager_events_manager_proto_rawDescData = file_manager_events_manager_proto_rawDesc
)

func file_manager_events_manager_proto_rawDescGZIP() []byte {
	file_manager_events_manager_proto_rawDescOnce.Do(func() {
		file_manager_events_manager_proto_rawDescData = protoimpl.X.CompressGZIP(file_manager_events_manager_proto_rawDescData)
	})
	return file_manager_events_manager_proto_rawDescData
}

var file_manager_events_manager_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_manager_events_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_manager_events_manager_proto_goTypes = []interface{}{
	(ManagerRole)(0),              // 0: api.manager.events.ManagerRole
	(*ManagerEvent)(nil),          // 1: api.manager.events.ManagerEvent
	(*ManagerCreated)(nil),        // 2: api.manager.events.ManagerCreated
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_manager_events_manager_proto_depIdxs = []int32{
	2, // 0: api.manager.events.ManagerEvent.managerCreated:type_name -> api.manager.events.ManagerCreated
	0, // 1: api.manager.events.ManagerCreated.role:type_name -> api.manager.events.ManagerRole
	3, // 2: api.manager.events.ManagerCreated.createdAt:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_manager_events_manager_proto_init() }
func file_manager_events_manager_proto_init() {
	if File_manager_events_manager_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_manager_events_manager_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_manager_events_manager_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ManagerCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_manager_events_manager_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ManagerEvent_ManagerCreated)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_manager_events_manager_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_manager_events_manager_proto_goTypes,
		DependencyIndexes: file_manager_events_manager_proto_depIdxs,
		EnumInfos:         file_manager_events_manager_proto_enumTypes,
		MessageInfos:      file_manager_events_manager_proto_msgTypes,
	}.Build()
	File_manager_events_manager_proto = out.File
	file_manager_events_manager_proto_rawDesc = nil
	file_manager_events_manager_proto_goTypes = nil
	file_manager_events_manager_proto_depIdxs = nil
}
