// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: account/events/credit_accout.proto

package events

import (
	common "github.com/fabl3ss/banking_system/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditAccountEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// Types that are assignable to Event:
	//
	//	*CreditAccountEvent_AccountCreated
	//	*CreditAccountEvent_AccountCreateFailed
	//	*CreditAccountEvent_AccountApproved
	//	*CreditAccountEvent_AccountApproveFailed
	//	*CreditAccountEvent_AccountClosed
	//	*CreditAccountEvent_AccountCloseFailed
	Event isCreditAccountEvent_Event `protobuf_oneof:"event"`
}

func (x *CreditAccountEvent) Reset() {
	*x = CreditAccountEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountEvent) ProtoMessage() {}

func (x *CreditAccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountEvent.ProtoReflect.Descriptor instead.
func (*CreditAccountEvent) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{0}
}

func (x *CreditAccountEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (m *CreditAccountEvent) GetEvent() isCreditAccountEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountCreated() *CreditAccountCreated {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountCreated); ok {
		return x.AccountCreated
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountCreateFailed() *CreditAccountCreateFailed {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountCreateFailed); ok {
		return x.AccountCreateFailed
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountApproved() *CreditAccountApproved {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountApproved); ok {
		return x.AccountApproved
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountApproveFailed() *CreditAccountApproveFailed {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountApproveFailed); ok {
		return x.AccountApproveFailed
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountClosed() *CreditAccountClosed {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountClosed); ok {
		return x.AccountClosed
	}
	return nil
}

func (x *CreditAccountEvent) GetAccountCloseFailed() *CreditAccountCloseFailed {
	if x, ok := x.GetEvent().(*CreditAccountEvent_AccountCloseFailed); ok {
		return x.AccountCloseFailed
	}
	return nil
}

type isCreditAccountEvent_Event interface {
	isCreditAccountEvent_Event()
}

type CreditAccountEvent_AccountCreated struct {
	AccountCreated *CreditAccountCreated `protobuf:"bytes,2,opt,name=accountCreated,proto3,oneof"`
}

type CreditAccountEvent_AccountCreateFailed struct {
	AccountCreateFailed *CreditAccountCreateFailed `protobuf:"bytes,3,opt,name=accountCreateFailed,proto3,oneof"`
}

type CreditAccountEvent_AccountApproved struct {
	AccountApproved *CreditAccountApproved `protobuf:"bytes,4,opt,name=accountApproved,proto3,oneof"`
}

type CreditAccountEvent_AccountApproveFailed struct {
	AccountApproveFailed *CreditAccountApproveFailed `protobuf:"bytes,5,opt,name=accountApproveFailed,proto3,oneof"`
}

type CreditAccountEvent_AccountClosed struct {
	AccountClosed *CreditAccountClosed `protobuf:"bytes,6,opt,name=accountClosed,proto3,oneof"`
}

type CreditAccountEvent_AccountCloseFailed struct {
	AccountCloseFailed *CreditAccountCloseFailed `protobuf:"bytes,7,opt,name=accountCloseFailed,proto3,oneof"`
}

func (*CreditAccountEvent_AccountCreated) isCreditAccountEvent_Event() {}

func (*CreditAccountEvent_AccountCreateFailed) isCreditAccountEvent_Event() {}

func (*CreditAccountEvent_AccountApproved) isCreditAccountEvent_Event() {}

func (*CreditAccountEvent_AccountApproveFailed) isCreditAccountEvent_Event() {}

func (*CreditAccountEvent_AccountClosed) isCreditAccountEvent_Event() {}

func (*CreditAccountEvent_AccountCloseFailed) isCreditAccountEvent_Event() {}

type CreditAccountCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HolderId        string                 `protobuf:"bytes,1,opt,name=holderId,proto3" json:"holderId,omitempty"`
	Balance         *common.Money          `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	OpenedAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=openedAt,proto3" json:"openedAt,omitempty"`
	ExpiryDate      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	Limit           int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Debt            int64                  `protobuf:"varint,6,opt,name=debt,proto3" json:"debt,omitempty"`
	AccruedInterest int32                  `protobuf:"varint,7,opt,name=accruedInterest,proto3" json:"accruedInterest,omitempty"`
	CreditRate      int32                  `protobuf:"varint,8,opt,name=creditRate,proto3" json:"creditRate,omitempty"`
}

func (x *CreditAccountCreated) Reset() {
	*x = CreditAccountCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountCreated) ProtoMessage() {}

func (x *CreditAccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountCreated.ProtoReflect.Descriptor instead.
func (*CreditAccountCreated) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{1}
}

func (x *CreditAccountCreated) GetHolderId() string {
	if x != nil {
		return x.HolderId
	}
	return ""
}

func (x *CreditAccountCreated) GetBalance() *common.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *CreditAccountCreated) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

func (x *CreditAccountCreated) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *CreditAccountCreated) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CreditAccountCreated) GetDebt() int64 {
	if x != nil {
		return x.Debt
	}
	return 0
}

func (x *CreditAccountCreated) GetAccruedInterest() int32 {
	if x != nil {
		return x.AccruedInterest
	}
	return 0
}

func (x *CreditAccountCreated) GetCreditRate() int32 {
	if x != nil {
		return x.CreditRate
	}
	return 0
}

type CreditAccountCreateFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreditAccountCreateFailed) Reset() {
	*x = CreditAccountCreateFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountCreateFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountCreateFailed) ProtoMessage() {}

func (x *CreditAccountCreateFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountCreateFailed.ProtoReflect.Descriptor instead.
func (*CreditAccountCreateFailed) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{2}
}

func (x *CreditAccountCreateFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreditAccountApproved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManagerId    string                 `protobuf:"bytes,1,opt,name=managerId,proto3" json:"managerId,omitempty"`
	ApprovalTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=approvalTime,proto3" json:"approvalTime,omitempty"`
}

func (x *CreditAccountApproved) Reset() {
	*x = CreditAccountApproved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountApproved) ProtoMessage() {}

func (x *CreditAccountApproved) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountApproved.ProtoReflect.Descriptor instead.
func (*CreditAccountApproved) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{3}
}

func (x *CreditAccountApproved) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *CreditAccountApproved) GetApprovalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovalTime
	}
	return nil
}

type CreditAccountApproveFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreditAccountApproveFailed) Reset() {
	*x = CreditAccountApproveFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountApproveFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountApproveFailed) ProtoMessage() {}

func (x *CreditAccountApproveFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountApproveFailed.ProtoReflect.Descriptor instead.
func (*CreditAccountApproveFailed) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{4}
}

func (x *CreditAccountApproveFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreditAccountClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClosedTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=closedTime,proto3" json:"closedTime,omitempty"`
}

func (x *CreditAccountClosed) Reset() {
	*x = CreditAccountClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountClosed) ProtoMessage() {}

func (x *CreditAccountClosed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountClosed.ProtoReflect.Descriptor instead.
func (*CreditAccountClosed) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{5}
}

func (x *CreditAccountClosed) GetClosedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedTime
	}
	return nil
}

type CreditAccountCloseFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *CreditAccountCloseFailed) Reset() {
	*x = CreditAccountCloseFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_credit_accout_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreditAccountCloseFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditAccountCloseFailed) ProtoMessage() {}

func (x *CreditAccountCloseFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_credit_accout_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditAccountCloseFailed.ProtoReflect.Descriptor instead.
func (*CreditAccountCloseFailed) Descriptor() ([]byte, []int) {
	return file_account_events_credit_accout_proto_rawDescGZIP(), []int{6}
}

func (x *CreditAccountCloseFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_account_events_credit_accout_proto protoreflect.FileDescriptor

var file_account_events_credit_accout_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe0, 0x04,
	0x0a, 0x12, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x45,
	0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x52, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e,
	0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x61, 0x0a, 0x13, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c,
	0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x55, 0x0a, 0x0f, 0x61, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x29, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x48, 0x00, 0x52,
	0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x12, 0x64, 0x0a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x4f, 0x0a, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x5e, 0x0a, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x48, 0x00, 0x52, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73,
	0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x22, 0xc7, 0x02, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6c,
	0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x2b, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x79, 0x44, 0x61, 0x74, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x65, 0x62, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x64, 0x65, 0x62, 0x74,
	0x12, 0x28, 0x0a, 0x0f, 0x61, 0x63, 0x63, 0x72, 0x75, 0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x65, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x72, 0x75,
	0x65, 0x64, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a,
	0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x52, 0x61, 0x74, 0x65, 0x22, 0x3d, 0x0a, 0x19, 0x43, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x75, 0x0a, 0x15, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76,
	0x65, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x3e, 0x0a, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65,
	0x22, 0x3e, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x51, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x3c, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12,
	0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_events_credit_accout_proto_rawDescOnce sync.Once
	file_account_events_credit_accout_proto_rawDescData = file_account_events_credit_accout_proto_rawDesc
)

func file_account_events_credit_accout_proto_rawDescGZIP() []byte {
	file_account_events_credit_accout_proto_rawDescOnce.Do(func() {
		file_account_events_credit_accout_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_events_credit_accout_proto_rawDescData)
	})
	return file_account_events_credit_accout_proto_rawDescData
}

var file_account_events_credit_accout_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_account_events_credit_accout_proto_goTypes = []interface{}{
	(*CreditAccountEvent)(nil),         // 0: api.account.events.CreditAccountEvent
	(*CreditAccountCreated)(nil),       // 1: api.account.events.CreditAccountCreated
	(*CreditAccountCreateFailed)(nil),  // 2: api.account.events.CreditAccountCreateFailed
	(*CreditAccountApproved)(nil),      // 3: api.account.events.CreditAccountApproved
	(*CreditAccountApproveFailed)(nil), // 4: api.account.events.CreditAccountApproveFailed
	(*CreditAccountClosed)(nil),        // 5: api.account.events.CreditAccountClosed
	(*CreditAccountCloseFailed)(nil),   // 6: api.account.events.CreditAccountCloseFailed
	(*common.Money)(nil),               // 7: api.common.Money
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
}
var file_account_events_credit_accout_proto_depIdxs = []int32{
	1,  // 0: api.account.events.CreditAccountEvent.accountCreated:type_name -> api.account.events.CreditAccountCreated
	2,  // 1: api.account.events.CreditAccountEvent.accountCreateFailed:type_name -> api.account.events.CreditAccountCreateFailed
	3,  // 2: api.account.events.CreditAccountEvent.accountApproved:type_name -> api.account.events.CreditAccountApproved
	4,  // 3: api.account.events.CreditAccountEvent.accountApproveFailed:type_name -> api.account.events.CreditAccountApproveFailed
	5,  // 4: api.account.events.CreditAccountEvent.accountClosed:type_name -> api.account.events.CreditAccountClosed
	6,  // 5: api.account.events.CreditAccountEvent.accountCloseFailed:type_name -> api.account.events.CreditAccountCloseFailed
	7,  // 6: api.account.events.CreditAccountCreated.balance:type_name -> api.common.Money
	8,  // 7: api.account.events.CreditAccountCreated.openedAt:type_name -> google.protobuf.Timestamp
	8,  // 8: api.account.events.CreditAccountCreated.expiryDate:type_name -> google.protobuf.Timestamp
	8,  // 9: api.account.events.CreditAccountApproved.approvalTime:type_name -> google.protobuf.Timestamp
	8,  // 10: api.account.events.CreditAccountClosed.closedTime:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_account_events_credit_accout_proto_init() }
func file_account_events_credit_accout_proto_init() {
	if File_account_events_credit_accout_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_events_credit_accout_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountCreateFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountApproved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountApproveFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_credit_accout_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreditAccountCloseFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_account_events_credit_accout_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*CreditAccountEvent_AccountCreated)(nil),
		(*CreditAccountEvent_AccountCreateFailed)(nil),
		(*CreditAccountEvent_AccountApproved)(nil),
		(*CreditAccountEvent_AccountApproveFailed)(nil),
		(*CreditAccountEvent_AccountClosed)(nil),
		(*CreditAccountEvent_AccountCloseFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_events_credit_accout_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_events_credit_accout_proto_goTypes,
		DependencyIndexes: file_account_events_credit_accout_proto_depIdxs,
		MessageInfos:      file_account_events_credit_accout_proto_msgTypes,
	}.Build()
	File_account_events_credit_accout_proto = out.File
	file_account_events_credit_accout_proto_rawDesc = nil
	file_account_events_credit_accout_proto_goTypes = nil
	file_account_events_credit_accout_proto_depIdxs = nil
}
