// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: account/events/deposit_account.proto

package events

import (
	common "github.com/fabl3ss/banking_system/api/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepositAccountEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// Types that are assignable to Event:
	//
	//	*DepositAccountEvent_AccountCreated
	//	*DepositAccountEvent_AccountCreateFailed
	//	*DepositAccountEvent_AccountApproved
	//	*DepositAccountEvent_AccountApproveFailed
	//	*DepositAccountEvent_AccountClosed
	//	*DepositAccountEvent_AccountCloseFailed
	Event isDepositAccountEvent_Event `protobuf_oneof:"event"`
}

func (x *DepositAccountEvent) Reset() {
	*x = DepositAccountEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountEvent) ProtoMessage() {}

func (x *DepositAccountEvent) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountEvent.ProtoReflect.Descriptor instead.
func (*DepositAccountEvent) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{0}
}

func (x *DepositAccountEvent) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (m *DepositAccountEvent) GetEvent() isDepositAccountEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountCreated() *DepositAccountCreated {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountCreated); ok {
		return x.AccountCreated
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountCreateFailed() *DepositAccountCreateFailed {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountCreateFailed); ok {
		return x.AccountCreateFailed
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountApproved() *DepositAccountApproved {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountApproved); ok {
		return x.AccountApproved
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountApproveFailed() *DepositAccountApproveFailed {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountApproveFailed); ok {
		return x.AccountApproveFailed
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountClosed() *DepositAccountClosed {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountClosed); ok {
		return x.AccountClosed
	}
	return nil
}

func (x *DepositAccountEvent) GetAccountCloseFailed() *DepositAccountCloseFailed {
	if x, ok := x.GetEvent().(*DepositAccountEvent_AccountCloseFailed); ok {
		return x.AccountCloseFailed
	}
	return nil
}

type isDepositAccountEvent_Event interface {
	isDepositAccountEvent_Event()
}

type DepositAccountEvent_AccountCreated struct {
	AccountCreated *DepositAccountCreated `protobuf:"bytes,2,opt,name=accountCreated,proto3,oneof"`
}

type DepositAccountEvent_AccountCreateFailed struct {
	AccountCreateFailed *DepositAccountCreateFailed `protobuf:"bytes,3,opt,name=accountCreateFailed,proto3,oneof"`
}

type DepositAccountEvent_AccountApproved struct {
	AccountApproved *DepositAccountApproved `protobuf:"bytes,4,opt,name=accountApproved,proto3,oneof"`
}

type DepositAccountEvent_AccountApproveFailed struct {
	AccountApproveFailed *DepositAccountApproveFailed `protobuf:"bytes,5,opt,name=accountApproveFailed,proto3,oneof"`
}

type DepositAccountEvent_AccountClosed struct {
	AccountClosed *DepositAccountClosed `protobuf:"bytes,6,opt,name=accountClosed,proto3,oneof"`
}

type DepositAccountEvent_AccountCloseFailed struct {
	AccountCloseFailed *DepositAccountCloseFailed `protobuf:"bytes,7,opt,name=accountCloseFailed,proto3,oneof"`
}

func (*DepositAccountEvent_AccountCreated) isDepositAccountEvent_Event() {}

func (*DepositAccountEvent_AccountCreateFailed) isDepositAccountEvent_Event() {}

func (*DepositAccountEvent_AccountApproved) isDepositAccountEvent_Event() {}

func (*DepositAccountEvent_AccountApproveFailed) isDepositAccountEvent_Event() {}

func (*DepositAccountEvent_AccountClosed) isDepositAccountEvent_Event() {}

func (*DepositAccountEvent_AccountCloseFailed) isDepositAccountEvent_Event() {}

type DepositAccountCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HolderId      string                 `protobuf:"bytes,1,opt,name=holderId,proto3" json:"holderId,omitempty"`
	Balance       *common.Money          `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	OpenedAt      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=openedAt,proto3" json:"openedAt,omitempty"`
	ExpiryDate    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiryDate,proto3" json:"expiryDate,omitempty"`
	DepositAmount int64                  `protobuf:"varint,5,opt,name=depositAmount,proto3" json:"depositAmount,omitempty"`
	AnnualRate    int32                  `protobuf:"varint,6,opt,name=annualRate,proto3" json:"annualRate,omitempty"`
}

func (x *DepositAccountCreated) Reset() {
	*x = DepositAccountCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountCreated) ProtoMessage() {}

func (x *DepositAccountCreated) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountCreated.ProtoReflect.Descriptor instead.
func (*DepositAccountCreated) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{1}
}

func (x *DepositAccountCreated) GetHolderId() string {
	if x != nil {
		return x.HolderId
	}
	return ""
}

func (x *DepositAccountCreated) GetBalance() *common.Money {
	if x != nil {
		return x.Balance
	}
	return nil
}

func (x *DepositAccountCreated) GetOpenedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OpenedAt
	}
	return nil
}

func (x *DepositAccountCreated) GetExpiryDate() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiryDate
	}
	return nil
}

func (x *DepositAccountCreated) GetDepositAmount() int64 {
	if x != nil {
		return x.DepositAmount
	}
	return 0
}

func (x *DepositAccountCreated) GetAnnualRate() int32 {
	if x != nil {
		return x.AnnualRate
	}
	return 0
}

type DepositAccountCreateFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DepositAccountCreateFailed) Reset() {
	*x = DepositAccountCreateFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountCreateFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountCreateFailed) ProtoMessage() {}

func (x *DepositAccountCreateFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountCreateFailed.ProtoReflect.Descriptor instead.
func (*DepositAccountCreateFailed) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{2}
}

func (x *DepositAccountCreateFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DepositAccountApproved struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ManagerId    string                 `protobuf:"bytes,1,opt,name=managerId,proto3" json:"managerId,omitempty"`
	ApprovalTime *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=approvalTime,proto3" json:"approvalTime,omitempty"`
}

func (x *DepositAccountApproved) Reset() {
	*x = DepositAccountApproved{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountApproved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountApproved) ProtoMessage() {}

func (x *DepositAccountApproved) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountApproved.ProtoReflect.Descriptor instead.
func (*DepositAccountApproved) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{3}
}

func (x *DepositAccountApproved) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *DepositAccountApproved) GetApprovalTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovalTime
	}
	return nil
}

type DepositAccountApproveFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DepositAccountApproveFailed) Reset() {
	*x = DepositAccountApproveFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountApproveFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountApproveFailed) ProtoMessage() {}

func (x *DepositAccountApproveFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountApproveFailed.ProtoReflect.Descriptor instead.
func (*DepositAccountApproveFailed) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{4}
}

func (x *DepositAccountApproveFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DepositAccountClosed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClosedTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=closedTime,proto3" json:"closedTime,omitempty"`
}

func (x *DepositAccountClosed) Reset() {
	*x = DepositAccountClosed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountClosed) ProtoMessage() {}

func (x *DepositAccountClosed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountClosed.ProtoReflect.Descriptor instead.
func (*DepositAccountClosed) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{5}
}

func (x *DepositAccountClosed) GetClosedTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedTime
	}
	return nil
}

type DepositAccountCloseFailed struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *DepositAccountCloseFailed) Reset() {
	*x = DepositAccountCloseFailed{}
	if protoimpl.UnsafeEnabled {
		mi := &file_account_events_deposit_account_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DepositAccountCloseFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepositAccountCloseFailed) ProtoMessage() {}

func (x *DepositAccountCloseFailed) ProtoReflect() protoreflect.Message {
	mi := &file_account_events_deposit_account_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepositAccountCloseFailed.ProtoReflect.Descriptor instead.
func (*DepositAccountCloseFailed) Descriptor() ([]byte, []int) {
	return file_account_events_deposit_account_proto_rawDescGZIP(), []int{6}
}

func (x *DepositAccountCloseFailed) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_account_events_deposit_account_proto protoreflect.FileDescriptor

var file_account_events_deposit_account_proto_rawDesc = []byte{
	0x0a, 0x24, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xe7, 0x04, 0x0a, 0x13, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x53, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x62, 0x0a, 0x13, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x13, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x56,
	0x0a, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f,
	0x76, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70,
	0x70, 0x72, 0x6f, 0x76, 0x65, 0x64, 0x12, 0x65, 0x0a, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x14, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x50, 0x0a,
	0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12,
	0x5f, 0x0a, 0x12, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46,
	0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73,
	0x2e, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x48, 0x00, 0x52, 0x12, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x9a, 0x02, 0x0a, 0x15, 0x44, 0x65,
	0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x2b, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x6f,
	0x6e, 0x65, 0x79, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x08,
	0x6f, 0x70, 0x65, 0x6e, 0x65, 0x64, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x6f, 0x70, 0x65, 0x6e,
	0x65, 0x64, 0x41, 0x74, 0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61,
	0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x24, 0x0a, 0x0d, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x6e, 0x6e, 0x75, 0x61, 0x6c,
	0x52, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x61, 0x6e, 0x6e, 0x75,
	0x61, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x22, 0x3e, 0x0a, 0x1a, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x46, 0x61,
	0x69, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x76, 0x0a, 0x16, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x64,
	0x12, 0x1c, 0x0a, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x49, 0x64, 0x12, 0x3e,
	0x0a, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x3f,
	0x0a, 0x1b, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x52, 0x0a, 0x14, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12, 0x3a, 0x0a, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0a, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x54,
	0x69, 0x6d, 0x65, 0x22, 0x3d, 0x0a, 0x19, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x42, 0x10, 0x5a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_account_events_deposit_account_proto_rawDescOnce sync.Once
	file_account_events_deposit_account_proto_rawDescData = file_account_events_deposit_account_proto_rawDesc
)

func file_account_events_deposit_account_proto_rawDescGZIP() []byte {
	file_account_events_deposit_account_proto_rawDescOnce.Do(func() {
		file_account_events_deposit_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_account_events_deposit_account_proto_rawDescData)
	})
	return file_account_events_deposit_account_proto_rawDescData
}

var file_account_events_deposit_account_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_account_events_deposit_account_proto_goTypes = []interface{}{
	(*DepositAccountEvent)(nil),         // 0: api.account.events.DepositAccountEvent
	(*DepositAccountCreated)(nil),       // 1: api.account.events.DepositAccountCreated
	(*DepositAccountCreateFailed)(nil),  // 2: api.account.events.DepositAccountCreateFailed
	(*DepositAccountApproved)(nil),      // 3: api.account.events.DepositAccountApproved
	(*DepositAccountApproveFailed)(nil), // 4: api.account.events.DepositAccountApproveFailed
	(*DepositAccountClosed)(nil),        // 5: api.account.events.DepositAccountClosed
	(*DepositAccountCloseFailed)(nil),   // 6: api.account.events.DepositAccountCloseFailed
	(*common.Money)(nil),                // 7: api.common.Money
	(*timestamppb.Timestamp)(nil),       // 8: google.protobuf.Timestamp
}
var file_account_events_deposit_account_proto_depIdxs = []int32{
	1,  // 0: api.account.events.DepositAccountEvent.accountCreated:type_name -> api.account.events.DepositAccountCreated
	2,  // 1: api.account.events.DepositAccountEvent.accountCreateFailed:type_name -> api.account.events.DepositAccountCreateFailed
	3,  // 2: api.account.events.DepositAccountEvent.accountApproved:type_name -> api.account.events.DepositAccountApproved
	4,  // 3: api.account.events.DepositAccountEvent.accountApproveFailed:type_name -> api.account.events.DepositAccountApproveFailed
	5,  // 4: api.account.events.DepositAccountEvent.accountClosed:type_name -> api.account.events.DepositAccountClosed
	6,  // 5: api.account.events.DepositAccountEvent.accountCloseFailed:type_name -> api.account.events.DepositAccountCloseFailed
	7,  // 6: api.account.events.DepositAccountCreated.balance:type_name -> api.common.Money
	8,  // 7: api.account.events.DepositAccountCreated.openedAt:type_name -> google.protobuf.Timestamp
	8,  // 8: api.account.events.DepositAccountCreated.expiryDate:type_name -> google.protobuf.Timestamp
	8,  // 9: api.account.events.DepositAccountApproved.approvalTime:type_name -> google.protobuf.Timestamp
	8,  // 10: api.account.events.DepositAccountClosed.closedTime:type_name -> google.protobuf.Timestamp
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_account_events_deposit_account_proto_init() }
func file_account_events_deposit_account_proto_init() {
	if File_account_events_deposit_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_account_events_deposit_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountCreateFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountApproved); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountApproveFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountClosed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_account_events_deposit_account_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DepositAccountCloseFailed); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_account_events_deposit_account_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*DepositAccountEvent_AccountCreated)(nil),
		(*DepositAccountEvent_AccountCreateFailed)(nil),
		(*DepositAccountEvent_AccountApproved)(nil),
		(*DepositAccountEvent_AccountApproveFailed)(nil),
		(*DepositAccountEvent_AccountClosed)(nil),
		(*DepositAccountEvent_AccountCloseFailed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_account_events_deposit_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_events_deposit_account_proto_goTypes,
		DependencyIndexes: file_account_events_deposit_account_proto_depIdxs,
		MessageInfos:      file_account_events_deposit_account_proto_msgTypes,
	}.Build()
	File_account_events_deposit_account_proto = out.File
	file_account_events_deposit_account_proto_rawDesc = nil
	file_account_events_deposit_account_proto_goTypes = nil
	file_account_events_deposit_account_proto_depIdxs = nil
}
